language: node_js
node_js:
- stable
sudo: false
script: npm run $COMMAND
before_script:
- npm run lint
env:
  matrix:
  - COMMAND=test
  - COMMAND=test-browser
  - COMMAND=report-coverage
  global:
  - secure: ug76MyYP5+/TL0HOJVCg7dbB2lyN8efBoJ9CjRQxlkZbiOOXVXMEi86wifAe+xeZVnCrB0S+2EX0jFtezmg9az3f1ktuN5TcjSWPJhtM8MpqX0RBSGvQtNY5GeDfsQcVWL4C4eC/zADBPLAvdznsE5OlFYrO9TjSXiPwekabU8L9Oxk7Yq0yZ/WhSGooNL9B/yaGO/inRDa65Ch7yZwoND6L8UmF3R12FXQM6Sn6OAhUgWRKfYPjDfCfv8pXGLNYkllv9pCEj9C65+sP7k6OA5L7pBLQj6S6Bz0n7XIpaGfSHgnTLOvd4f6ebrLDa71+b/bSagNMKTuQ3pGvEibKtwBQv+HF2qHhf4rnVrUFSYaXFSvjIfN/GCO+DI1B5o8T6y2Gyy2wSPoLxbRa0sZiHRuHBpsS3WrAwxBKYyDMof5nVkBBje6Ih5IiwKKbsvCXhocEwX1CKXsqXHd/hopCOQra2v5PVUTBmjV2LdV1CsVIKXm0JYr0VE3ab7PMHpgjtUHgDP1cclGZqTAi8PtfWd98apMUbXoKqXW9v9+f6ARtz+IfHLtPqrjTe2dB38SnVsZqrsopiqxTVKgTcz1vY3FA8Wg3HLOuhD529a9sed/gYCxA/u+QSAo4WuysqWqf6sUyq6uSBFM2ClzdBTgIxcltgWrB4y35kFav1+WNtsQ=
  - secure: IaeC5qFM1EarirH1n5gARuuGG4OQBEccpjmZz34PyhbJyEB9wOmwgbsMrggDiu7bUAJTx6WPIzVagYiJyK/ATbhsZ0KJUSjXqErVyIE9+gn5PDm74/Y8sK6g1gUlqNml6D7D6xyx0DGgAQqJcqBxOTID49byAYFNSvHN+H8Rjqn6lyPnEUl0v8ptPyi/am6clCTT49EVnaQ077o/aZdkau/1gzDSKHS+9iKku89GHC9iAdBbZIt9gJtbnBjJM7bV8kIie7yUL2o6kEfPkciglt2PdpTLwxAPWXuVizHVh/BzFVHN8Pn6JiDOu9cwtnzu7NxLrOebZ8ItVsSC1uJKAU5qwUmusZaaR1RJKiccIfCdZIekI9AQx3cu/cccWrPa9MA45Wwm2ZA5EFpMkQispjAdtkIWp3ZD7xR/Dg5yXnGal6e+ARx8h2fHYMONxRcAYNXiD/iJfTO42BTjgOAVGfS18y+NX7LkMujtxTBrwt7it/hDrewDKrmod0xo734BShMaysOOv0HSLKPH3ChOQglmzhvdAyFGtRwBtyS+rTzk8HmSYf0nS0MCvRGOm04ZppsV7F/ncpgfWudCa80zfLfPIWIRdIH4WKr4lWimA+bBXrojJbvjBqM80JofAvdWR+I/fnZI5GzTIXWoQ0+MBKCzhDBO4L4aOisixkLeEg0=
  - secure: qA/t6j6P+Y/m0U1B5Ht9LPl/KMTU3L4v13tZIUIDP8ULplzr8A7nzAF9y1lIsThi/3941m+vAYU+AEcnGn3BSlDXh3XoTwOfUZJtgwL2SJyNZaekOHtK/CLNDKPhjL1jSSPwEl4K9rUUjMNJvF+3RzuJHpNHsjzYWS/PWcC0W9fZR2mapYSUmRzpgcYRM3821kpCd2eN++rhByqr/By2Z/2hdHD9iVTHo5DMHkGQmTCAqw1uabMhvmsDHod2r85dEFbDFaDeJWrtJNxhKhU2Jbr0TSFsoi+3oF2e2A0MP82waRvDKlB2UKmJu86m1mcPjVcidXFss1kIWsfIX+sCrLcd6FCzlh4veMGxvYnQ049aUnJa1R85p04Xv4m0yrR18Ay1IPAruyX4ojTFbRjdjUZOi/KZKJoN0Om7N+h8F7sf4BXWWWHuugNFoUtqPw3Qqxys+GeGPGXlXL99sLk9C1+Xo/O7XSZG+ZtNk5woEuq7stYZ8E4wddfWDvfokIszCHeknGCpVLJiKC3zDjV8slQbn6gL/qv/NXEvQPRMzXLwOAd8AOOCa73nT9h6T8IQr/0QV8IUD5Ec0epxIZRg1Kp0kMd5P8fWOBviXdFAoCbdi6pDAAZtpZD8hCgJ3guktabXXT25C+xSf2s1w4oAwrXpyHHY9QkHNnlGj1Meh74=
branches:
  only:
  - master
